### ISSUE TITLE
Feature Request: Revoke Server

### ISSUE THREAD

**Issue by stevenscg** [threatstack/threatstack-ansible#22]
Currently, I have to log into the web application and manually "Revoke Servers" as I terminate EC2 instances.

It would be great if I could add this role to my instance terminate playbook to revoke the server prior to terminating it.

If there is not a programmatic way to revoke servers, and there may be valid security reasons for that, then it would be good to note it here.

**Comment by tmclaugh** [comment]
@stevenscg, can you file a feature request with customer success?  There is no way to currently revoke an agent from the commandline.  If there becomes one we can add it of course.

**Comment by stevenscg** [comment]
@tmclaugh Is it best to make that request within the app or via email?

**Comment by tmclaugh** [comment]
@stevenscg Either one is fine.  They go to the same place.

**Comment by stevenscg** [comment]
Thanks! Filed.

**Comment by tmclaugh** [comment]
👍
