### ISSUE TITLE
SSL Certificate does not belong to app.threatstack.com.

### ISSUE THREAD

**Issue by blakeblackshear** [threatstack/threatstack-ansible#5]
Ansible task fails at `Add ThreatStack repo GPG key.` step in CentOS 7 with ansible 1.9.2.

```
SSL Certificate does not belong to app.threatstack.com.  Make sure the url has a certificate that belongs to it or use validate_certs=False
```

Running `sudo rpm --import https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK` directly works fine.

**Comment by apollocatlin** [comment]
I have disabled cert validation at this time. This is not an issue with our cert it belongs to app.threatstack.com, looking into issues in Ansible and python. Will update this ticket with links to relevant findings.
