### ISSUE TITLE
Installation failing under Ubuntu 22.04

### ISSUE THREAD

**Issue by EmniMike** [threatstack/threatstack-ansible#87]
Hi,

the role is not working for ubuntu 22.04 and fails with the following error:

`No package matching 'python-apt' is available`

Upon checking, the following packets may resolve the issue:
`However the following packages replace it:
  python-apt-doc python3-apt-dbg:i386 python3-apt:i386 python3-apt-dbg python3-apt python-apt-common
`

Most probably one of the two last mentioned packages are the ones required.

Regards,

Mike

**Comment by olhado** [comment]
Thanks for the heads up @EmniMike  . Should be fixed in the next release.

**Comment by olhado** [comment]
I believe this is fixed in #89
