### ISSUE TITLE
Issue with  ansible.builtin.include  

### ISSUE THREAD

**Issue by harsha-chamarthi** [threatstack/threatstack-ansible#92]
I am getting the below error when i am installing on Ubuntu 22.04 

` ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.`

Is it possible to replace include with include_tasks ?

**Comment by olhado** [comment]
Hi @harsha-chamarthi ,

Could you also email support so we can link this issue with your company account?

Thanks!

**Comment by harsha-chamarthi** [comment]
@olhado We have emailed support and they repsonded that it will be directed to the team which maintains the ansible role.

**Comment by harsha-chamarthi** [comment]
@olhado For now i am reverting to using a older version ansible-core 2.12 as a workaround. But you might have to update the playbook to support more latest versions of ansible in the future.
