### ISSUE TITLE
Issue with agent installation

### ISSUE THREAD

**Issue by harsha-chamarthi** [threatstack/threatstack-ansible#93]
Hi Team,
Getting the below error while running the threatstack agent install role, 
TASK [threatstack.threatstack-ansible : apt -- Add agent repository key] *******
 fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to download key at https://app.threatstack.com/APT-GPG-KEY-THREATSTACK: Request failed: <urlopen error [Errno -2] Name or service not known>"}

I am getting the below error while try to do a curl,
curl https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
curl: (6) Could not resolve host: app.threatstack.com

Please help

**Comment by yankeehacker** [comment]
Might have something to do with this: https://www.linkedin.com/posts/pcable_today-i-remove-the-dns-records-and-begin-activity-7213527210324824066-YYhK

**Comment by harsha-chamarthi** [comment]
@yankeehacker Thanks for the info. Closing the issue
